name: Docker Django CI

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout du code
        uses: actions/checkout@v3

      - name: Construction de l'image Docker
        run: docker build -t messagerie-app .

      - name: Ex√©cution des Tests dans le conteneur
        run: docker run messagerie-app

  deploy: #partie CD
    needs: test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' && success()
    steps:
      - name: Checkout du code
        uses: actions/checkout@v3

      - name: Connexion au Github Container Registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
      - name: Build and Push Image (CD)
        run: |
          docker build -t ghcr.io/${{ github.repository }}:latest .
          docker push ghcr.io/${{ github.repository }}:latest