name: Pipeline Messagerie DevOps

on:
  push:
    branches: [ main ]

jobs:
  # 1. JOB DE TEST (L'Intégration Continue - CI)
  integration-continue:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build de l'image de test
        run: docker build -t test-image .

      - name: Exécution des tests unitaires
        run: docker run test-image python manage.py test

  # 2. JOB DE LIVRAISON (Le Déploiement Continu - CD)
  livraison-continue:
    runs-on: ubuntu-latest
    needs: integration-continue # IMPORTANT : Ne se lance que si les tests passent
    permissions:
      contents: read
      packages: write
    
    steps:
      - uses: actions/checkout@v4

      - name: Connexion au Registry (GHCR)
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build et Push de l'image finale
        run: |
          # Mise en minuscule du nom de l'image pour Docker
          IMAGE_ID=ghcr.io/${{ github.repository }}
          IMAGE_ID=$(echo $IMAGE_ID | tr '[A-Z]' '[a-z]')
          
          docker build -t $IMAGE_ID:latest .
          docker push $IMAGE_ID:latest

  # 3. JOB DE DEPLOIEMENT (Mise en production - CD)
  deploiement-production:
    runs-on: ubuntu-latest
    needs: livraison-continue # Ne se lance que si l'image est publiée
    steps:
      - name: Déclenchement du déploiement sur Render
        # Ici on simule l'appel au serveur de prod (WebHook Render)
        run: curl -X POST ${{ secrets.RENDER_DEPLOY_HOOK }}