name: Pipeline Messagerie DevOps

on:
  push:
    branches: [ main ]

jobs:
  # 1. JOB DE TEST (L'Intégration Continue - CI)
  integration-continue:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Création du fichier .env pour les tests
        run: |
          echo "POSTGRES_DB=test_db" >> .env
          echo "POSTGRES_USER=test_user" >> .env
          echo "POSTGRES_PASSWORD=test_password" >> .env
          echo "SECRET_KEY=une-cle-secrete-pour-les-tests" >> .env
          echo "DEBUG=1" >> .env
          echo "DB_HOST=db" >> .env
          echo "DB_PORT=5432" >> .env
      - name: lancement des migrations avant les tests
        run: |
          docker compose run --build --rm web python manage.py makemigrations
          docker compose run --build --rm web python manage.py migrate --noinput

      - name: Lancement des tests avec Docker Compose
        # 'docker-compose run' démarre les dépendances ('db') et exécute la commande dans un nouveau conteneur 'web'
        run: docker compose run --build --rm web python manage.py test

  # 2. JOB DE LIVRAISON (Le Déploiement Continu - CD)
  livraison-continue:
    runs-on: ubuntu-latest
    needs: integration-continue # IMPORTANT : Ne se lance que si les tests passent
    permissions:
      contents: read
      packages: write
    
    steps:
      - uses: actions/checkout@v4

      - name: Connexion au Registry (GHCR)
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build et Push de l'image finale
        run: |
          # Mise en minuscule du nom de l'image pour Docker
          IMAGE_ID=ghcr.io/${{ github.repository }}
          IMAGE_ID=$(echo $IMAGE_ID | tr '[A-Z]' '[a-z]')
          
          docker build -t $IMAGE_ID:latest .
          docker push $IMAGE_ID:latest