name: Docker Django CI

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout du code
        uses: actions/checkout@v3

      - name: Construction de l'image Docker
        run: docker build -t messagerie-app .

      - name: Exécution des Tests dans le conteneur
        run: docker run messagerie-app

  deploy: #partie CD
    needs: test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' && success()
    steps:
      - name: Checkout du code
        uses: actions/checkout@v3

      - name: Connexion au registre GitHub
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Publier l'image (CD - Livraison)
        run: |
          # On donne un nom pro à l'image (en minuscules)
          IMAGE_ID=ghcr.io/${{ github.repository }}
          IMAGE_ID=$(echo $IMAGE_ID | tr '[A-Z]' '[a-z]')
          
          docker build -t $IMAGE_ID:latest .
          docker push $IMAGE_ID:latest